//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configuration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigurationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Configuration.Resources.ConfigurationResource", typeof(ConfigurationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appsettings.json.
        /// </summary>
        public static string CONFIG_FILE {
            get {
                return ResourceManager.GetString("CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoReplenishment.
        /// </summary>
        public static string CONFIG_RATE_LIMIT_AUTO_REPLENISHMENT {
            get {
                return ResourceManager.GetString("CONFIG_RATE_LIMIT_AUTO_REPLENISHMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermitLimit.
        /// </summary>
        public static string CONFIG_RATE_LIMIT_PERMIT_LIMIT {
            get {
                return ResourceManager.GetString("CONFIG_RATE_LIMIT_PERMIT_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueuLimit.
        /// </summary>
        public static string CONFIG_RATE_LIMIT_QUEULIMIT {
            get {
                return ResourceManager.GetString("CONFIG_RATE_LIMIT_QUEULIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplenishmentPeriod.
        /// </summary>
        public static string CONFIG_RATE_LIMIT_REPLENISHMENTPERIOD {
            get {
                return ResourceManager.GetString("CONFIG_RATE_LIMIT_REPLENISHMENTPERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiRateLimit.
        /// </summary>
        public static string CONFIG_RATE_LIMIT_SECTION {
            get {
                return ResourceManager.GetString("CONFIG_RATE_LIMIT_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SegmentsPerWindow.
        /// </summary>
        public static string CONFIG_RATE_LIMIT_SEGMENTS_PER_WINDOW {
            get {
                return ResourceManager.GetString("CONFIG_RATE_LIMIT_SEGMENTS_PER_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenLimit.
        /// </summary>
        public static string CONFIG_RATE_LIMIT_TOKEN_LIMIT {
            get {
                return ResourceManager.GetString("CONFIG_RATE_LIMIT_TOKEN_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenPerPeriod.
        /// </summary>
        public static string CONFIG_RATE_LIMIT_TOKEN_PER_PERIOD {
            get {
                return ResourceManager.GetString("CONFIG_RATE_LIMIT_TOKEN_PER_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string CONFIG_RATE_LIMIT_WINDOW {
            get {
                return ResourceManager.GetString("CONFIG_RATE_LIMIT_WINDOW", resourceCulture);
            }
        }
    }
}
